# DOCKER ENV

export APIGATEWAY_SERVICE_NAME="infra-apigateway"
export APIGATEWAY_SERVICE_IMAGE_NAME="apigateway-service"
export APIGATEWAY_SERVICE_IMAGE_VERSION="0.0.1"
export NETWORK_NAME="bridge-signature"

# DOCKER IMAGE UPDATE

if docker image inspect $APIGATEWAY_SERVICE_IMAGE_NAME:$APIGATEWAY_SERVICE_IMAGE_VERSION &> /dev/null; then
    docker image rm -f $APIGATEWAY_SERVICE_IMAGE_NAME:$APIGATEWAY_SERVICE_IMAGE_VERSION
fi
docker build -t $APIGATEWAY_SERVICE_IMAGE_NAME:$APIGATEWAY_SERVICE_IMAGE_VERSION .

# DOCKER SERVICE RUN

if [ "$(docker ps -aq -f name=$APIGATEWAY_SERVICE_NAME)" ]; then
    docker rm -f $APIGATEWAY_SERVICE_NAME
fi

docker run -d \
--network $NETWORK_NAME \
--name $APIGATEWAY_SERVICE_NAME \
-p $APIGATEWAY_SERVICE_PORT:$APIGATEWAY_SERVICE_PORT \
$APIGATEWAY_SERVICE_IMAGE_NAME:$APIGATEWAY_SERVICE_IMAGE_VERSION